locallibrary/catalog/urls.py
from django.urls import path, re_path
from . import views
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', RedirectView.as_view(url='/catalog', permanent = True)),
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse


class Genre(models.Model):
    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)"
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('genre-detail', args=[str(self.id)])

class Language(models.Model):
    name = models.CharField(max_length=200,
                            unique=True,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('language-detail', args=[str(self.id)])



class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book")
    imprint = models.CharField(max_length=200)
    isbn = models.CharField('ISBN', max_length=13,
                            unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn'
                                      '">ISBN number</a>')
    genre = models.ManyToManyField(
        Genre, help_text="Select a genre for this book")
    language = models.ForeignKey(
        'Language', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['title', 'author']

    def display_genre(self):
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = "Genre"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

import uuid
from datetime import date
from django.conf import settings

class BookInstance(models.Model):
    uniqueid = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    due_back = models.DateField(null=True, blank=True)

    @property
    def is_overdue(self):
        return bool(self.due_back and date.today() > self.due_back)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability')

    class Meta:
        ordering = ['due_back']

    def get_absolute_url(self):
        return reverse('bookinstance-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.uniqueid} ({self.book.title})'

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ["last_name"]

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"

locallibrary/catalog/views.py
from django.shortcuts import render
from .models import BookInstance, Author, Book, Genre
from django.views import generic

def index(request):
    word_books_are_filtered_by = 'foundation'
    num_books = Book.objects.count()
    num_instances = BookInstance.objects.count()
    num_genres = Genre.objects.count()
    num_books_with_word = Book.objects.filter(title__icontains=word_books_are_filtered_by).count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()

    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    return render(
        request,
        'index.html',
        context=
        {'num_books': num_books, 'num_instances': num_instances,
         'num_instances_available': num_instances_available, 'num_authors': num_authors,
         'num_genres': num_genres, 'num_books_with_word': num_books_with_word,
         'word': word_books_are_filtered_by, 'num_visits': num_visits}
    )

class BookListView(generic.ListView):
    model = Book
    paginate_by = 10

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

class AuthorDetailView(generic.DetailView):
    model = Author

locallibrary/catalog/templates/base_generic.html
<!doctype html>
<html lang="rus">
    <head>
        {% block title %}<title>Местная библиотека</title>{% endblock %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    {% block sidebar %}
                        <ul class="sidebar-nav">
                            <li><a href="{% url 'index' %}">Главная</a></li>
                            <li><a href="{% url 'books' %}">Все книги</a></li>
                            <li><a href="{% url 'authors' %}">Все авторы</a></li>
                        </ul>
                    {% endblock %}


                </div>
                <div class="col-sm-10 ">
                    {% block content %}{% endblock %}
                    {% block pagination %}
                        {% if is_paginated %}
                            <div class="pagination">
                                <span class="page-links">
                                    {% if page_obj.has_previous %}
                                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Предыдущая страница</a>
                                    {% endif %}
                                    <span class="page-current">
                                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                    </span>
                                    {% if page_obj.has_next %}
                                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Следующая страница</a>
                                    {% endif %}
                                </span>
                            </div>
                        {% endif %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>{{author.first_name}} {{author.last_name}}</h1>

    <p><strong>Дата рождения: </strong> {{ author.date_of_birth }}</p>
    <p><strong>Дата смерти:</strong> {{ author.date_of_death }}</p>

    <div style="margin-left:20px;margin-top: 20px">
        <h4>Список книг:</h4>
        {% for book in author.book_set.all %}
        <hr>
        <a href="{{book.get_absolute_url}}">{{book.title}}</a>
        {% endfor %}
    </div>
{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список авторов:</h1>

    {% if author_list %}
    <ul>

        {% for author in author_list %}
        <li>
            <a href="{{author.get_absolute_url}}">{{author.first_name}} {{author.last_name}}</a>
        </li>
        {% endfor %}

    </ul>
    {% else %}
        <p>В библиотеке нет записей об авторах.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Title: {{ book.title}}</h1>

    <p><strong>Автор:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
    <p><strong>Краткое содержание: </strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Язык:</strong> {{ book.language }}</p>
    <p><strong>Imprint:</strong> {{book.imprint}}</p>
    <p><strong>Жанры:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %},
    {% endif %}{% endfor %}</p>

    <div style="margin-left:20px;margin-top: 20px">
        <h4>Копии:</h4>
        {% for copy in book.bookinstance_set.all %}
        <hr>
        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %} text-danger{%else %} text-warning{% endif %}">{{ copy.get_status_display }}</p>
        {% if copy.status != 'a' %} <p><strong>Дата возврата:</strong> {{copy.due_back}}</p>
        {% endif %}
        <p class="text-muted"><strong>Id:</strong> {{copy.uniqueid}}</p>
        {% endfor %}
    </div>
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список книг:</h1>

    {% if book_list %}
    <ul>
        {% for book in book_list %}
        <li>
            <a href="{{book.get_absolute_url}}">{{ book.title}}</a> ({{book.author}})
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>В библиотеке нет книг.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Местная библиотека. Главная.</h1>

<p>Добро пожаловать в <em>Местную библиотеку</em>, очень простой Django-сайт, разработанный в качестве обучающего примера в Mozilla Developer Network.</p>
<h2>Динамический контент</h2>

<p>В библиотеке имеются следующие записи:</p>
<ul>
<li><strong>Книги:</strong> {{ num_books }}</li>
<li><strong>Копии:</strong> {{ num_instances }}</li>
<li><strong>Доступные копии:</strong> {{ num_instances_available }}</li>
<li><strong>Авторы:</strong> {{ num_authors }}</li>
<li><strong>Жанры:</strong> {{ num_genres }}</li>
<li><strong>Книги, содержащие слово {{ word }}:</strong> {{ num_books_with_word }}</li>
</ul>

<p>
    {% load templatetags %}
    Вы посетили эту страницу {{num_visits}} {{ num_visits|determine_word }}.
</p>
{% endblock %}